name: lab_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/nike.png
    - assets/adidas.png
    - assets/apple.png
    - assets/google.png
    - assets/carhartt.png
    - assets/dog.png

